name: check

on:
  push:
  pull_request:
  schedule:
    - cron: '45 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew buildPlugin -Pkotlin.incremental=false --no-daemon

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.2
        with:
          ide-versions: |
            ideaIC:2020.2
            ideaIC:LATEST-EAP-SNAPSHOT
